/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author canef
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accountManagement = new javax.swing.JPanel();
        headerAccmngmt = new javax.swing.JPanel();
        AccountManagement = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        confirmPassword = new javax.swing.JTextField();
        roleSelection = new javax.swing.JComboBox<>();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        accountsGrid = new javax.swing.JPanel();
        headerAccounts = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        librariesMngt = new javax.swing.JPanel();
        headerLibraries = new javax.swing.JPanel();
        LibrariesMngt = new javax.swing.JLabel();
        otherFees = new javax.swing.JButton();
        Tuition = new javax.swing.JButton();
        Books = new javax.swing.JButton();
        Uniforms = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(208, 229, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 99, 74));

        jLabel1.setBackground(new java.awt.Color(249, 228, 142));
        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 228, 142));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN SYSTEM");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1292, -1));

        accountManagement.setBackground(new java.awt.Color(172, 201, 182));
        accountManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 33, 24)));

        headerAccmngmt.setBackground(new java.awt.Color(48, 99, 74));

        AccountManagement.setBackground(new java.awt.Color(245, 249, 243));
        AccountManagement.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        AccountManagement.setForeground(new java.awt.Color(245, 249, 243));
        AccountManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccountManagement.setText("Account Management");

        javax.swing.GroupLayout headerAccmngmtLayout = new javax.swing.GroupLayout(headerAccmngmt);
        headerAccmngmt.setLayout(headerAccmngmtLayout);
        headerAccmngmtLayout.setHorizontalGroup(
            headerAccmngmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAccmngmtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccountManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerAccmngmtLayout.setVerticalGroup(
            headerAccmngmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAccmngmtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccountManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        roleSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Cashier", "Student" }));

        Email.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        Email.setText("Email:");

        Password.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        Password.setText("Password:");

        Role.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        Role.setText("Role");

        ConfirmPassword.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        ConfirmPassword.setText("Confirm Password");

        create.setBackground(new java.awt.Color(245, 249, 243));
        create.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        create.setText("CREATE");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountManagementLayout = new javax.swing.GroupLayout(accountManagement);
        accountManagement.setLayout(accountManagementLayout);
        accountManagementLayout.setHorizontalGroup(
            accountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerAccmngmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(accountManagementLayout.createSequentialGroup()
                .addGroup(accountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountManagementLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(accountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email)
                            .addGroup(accountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Password)
                            .addComponent(Role)
                            .addComponent(ConfirmPassword)))
                    .addGroup(accountManagementLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(accountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roleSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        accountManagementLayout.setVerticalGroup(
            accountManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountManagementLayout.createSequentialGroup()
                .addComponent(headerAccmngmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(Role)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel1.add(accountManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 480, 610));

        accountsGrid.setBackground(new java.awt.Color(172, 201, 182));
        accountsGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 33, 24)));

        headerAccounts.setBackground(new java.awt.Color(48, 99, 74));

        jLabel3.setBackground(new java.awt.Color(245, 249, 243));
        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 249, 243));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Accounts");

        javax.swing.GroupLayout headerAccountsLayout = new javax.swing.GroupLayout(headerAccounts);
        headerAccounts.setLayout(headerAccountsLayout);
        headerAccountsLayout.setHorizontalGroup(
            headerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerAccountsLayout.setVerticalGroup(
            headerAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"canefly@outlook.ph", "Student", "BSIT", "FULLY PAID"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Email", "Role", "Program", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout accountsGridLayout = new javax.swing.GroupLayout(accountsGrid);
        accountsGrid.setLayout(accountsGridLayout);
        accountsGridLayout.setHorizontalGroup(
            accountsGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(accountsGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountsGridLayout.setVerticalGroup(
            accountsGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsGridLayout.createSequentialGroup()
                .addComponent(headerAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(accountsGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 480, 610));

        librariesMngt.setBackground(new java.awt.Color(172, 201, 182));
        librariesMngt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 33, 24)));

        headerLibraries.setBackground(new java.awt.Color(48, 99, 74));

        LibrariesMngt.setBackground(new java.awt.Color(245, 249, 243));
        LibrariesMngt.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        LibrariesMngt.setForeground(new java.awt.Color(245, 249, 243));
        LibrariesMngt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LibrariesMngt.setText("Libraries Mngt");

        javax.swing.GroupLayout headerLibrariesLayout = new javax.swing.GroupLayout(headerLibraries);
        headerLibraries.setLayout(headerLibrariesLayout);
        headerLibrariesLayout.setHorizontalGroup(
            headerLibrariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLibrariesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibrariesMngt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerLibrariesLayout.setVerticalGroup(
            headerLibrariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLibrariesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibrariesMngt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        otherFees.setBackground(new java.awt.Color(245, 249, 243));
        otherFees.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        otherFees.setText("OTHER FEES");
        otherFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherFeesActionPerformed(evt);
            }
        });

        Tuition.setBackground(new java.awt.Color(245, 249, 243));
        Tuition.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        Tuition.setText("TUITION");
        Tuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuitionActionPerformed(evt);
            }
        });

        Books.setBackground(new java.awt.Color(245, 249, 243));
        Books.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        Books.setText("BOOKS");
        Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksActionPerformed(evt);
            }
        });

        Uniforms.setBackground(new java.awt.Color(245, 249, 243));
        Uniforms.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        Uniforms.setText("UNIFORMS");
        Uniforms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniformsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout librariesMngtLayout = new javax.swing.GroupLayout(librariesMngt);
        librariesMngt.setLayout(librariesMngtLayout);
        librariesMngtLayout.setHorizontalGroup(
            librariesMngtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLibraries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, librariesMngtLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(librariesMngtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(otherFees, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(librariesMngtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Uniforms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(Books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tuition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        librariesMngtLayout.setVerticalGroup(
            librariesMngtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librariesMngtLayout.createSequentialGroup()
                .addComponent(headerLibraries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Tuition, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Books, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Uniforms, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(otherFees, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 251, Short.MAX_VALUE))
        );

        jPanel1.add(librariesMngt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 280, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otherFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherFeesActionPerformed

    private void TuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuitionActionPerformed

    private void BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BooksActionPerformed

    private void UniformsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniformsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniformsActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountManagement;
    private javax.swing.JButton Books;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel LibrariesMngt;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Role;
    private javax.swing.JButton Tuition;
    private javax.swing.JButton Uniforms;
    private javax.swing.JPanel accountManagement;
    private javax.swing.JPanel accountsGrid;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JButton create;
    private javax.swing.JTextField email;
    private javax.swing.JPanel headerAccmngmt;
    private javax.swing.JPanel headerAccounts;
    private javax.swing.JPanel headerLibraries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel librariesMngt;
    private javax.swing.JButton otherFees;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> roleSelection;
    // End of variables declaration//GEN-END:variables
}
